### ISSUE TITLE
Header on connect

### ISSUE THREAD

**Issue by TechOverflow** [heminei/php-websocket#10]
Another user recently asked if the client could specify headers, but can the server reply with headers on connection?

`Upgrade: websocket` and `Connection: Upgrade` is probably a given, but headers like `Sec-WebSocket-Accept:` or `Sec-WebSocket-Protocol:`?

If `Sec-WebSocket-Protocol:` is already part of the code (I now see it is), can it be changed or would it have to be hardcoded? I believe that Ratchet uses a `getSubProtocols()` function.

Furthermore, can messages be sent to individual clients, not as a reply to a message, but simply sent any time while getting the reply back? With Ratchet this seems to be done by using extra libraries, which is slightly overkill for me. I need to receive messages from a client and on events on the server send messages to individual clients. Clients do not communicate together like in most of the examples out there.

**Comment by heminei** [comment]
I have implemented Sec-WebSocket-Protocol and Sec-WebSocket-Accept [(check here)](https://github.com/heminei/php-websocket/blob/master/src/HemiFrame/Lib/WebSocket/WebSocket.php#L859)

You can send messages to individual clients. You should connect with [PHP client](https://github.com/heminei/php-websocket/blob/master/demo/client.php) and send message to your server. After that, your server will send a message to selected clients.
