### ISSUE TITLE
How config nginx ?

### ISSUE THREAD

**Issue by ahvahsky2008** [heminei/php-websocket#16]
i try config nginx, but have troubles

![image](https://user-images.githubusercontent.com/8035828/73121780-f1a13000-3f8e-11ea-9924-b656ddff3ca2.png)
**index.html**
![image](https://user-images.githubusercontent.com/8035828/73121797-0bdb0e00-3f8f-11ea-846d-4f72a5f2578a.png)
**server.php**
![image](https://user-images.githubusercontent.com/8035828/73121800-201f0b00-3f8f-11ea-9e1b-22c83979e960.png)
and main page error
![image](https://user-images.githubusercontent.com/8035828/73121826-61afb600-3f8f-11ea-9cf7-dcb9ae7bbcf8.png)

**Comment by heminei** [comment]
In server.php do you call **$socket->startServer();** ?
