### ISSUE TITLE
Client on receive never called

### ISSUE THREAD

**Issue by printpagestopdf** [heminei/php-websocket#19]
Hello,

I am using exactly (different port) your client Example from the readme but $socket->on("receive", function($client, $data) use($socket)  is never called.

I am connecting to a python WS. Another (but weaker) PHP library receives data after calling.

On the WS Server I see Connection, receive the data, send data and see disconnecting, but the client receive is never called.

(For testing purposes I added a sleep(5) before disconnecting, same result.)

Best Regards

**Comment by heminei** [comment]
You should call `$socket->loop();` to listen for data.

Example
```php
<?php

require_once __DIR__ . '/../vendor/autoload.php';


$socket = new \HemiFrame\Lib\WebSocket\WebSocket("localhost", 8080);
$socket->setEnableLogging(true);

$client = $socket->connect();

$socket->on("receive", function (\HemiFrame\Lib\WebSocket\Client $client, $data) use ($socket) {
	var_dump($data);
});

$socket->loop();
```

Please check your logic. Usually, you should use PHP client to send data, not to receive.

**Comment by printpagestopdf** [comment]
Hi,
thank you for this fast answer will try it (probably tomorrow).
I read about loop in your doc, but its written there for the server (looping for server is obvious) perhaps a remark about using it for client could be helpfull for others? 

I implemented a server that is waiting for request, and depending on the request it sends data response. For this, my client sends and then waiting for a response.
BTW: Your implementation looks very mature.
Best Regards

    Am Montag, 4. Mai 2020, 23:00:56 MESZ hat Martin Bratvanov <notifications@github.com> Folgendes geschrieben:  
 
 


You should call $socket->loop(); to listen for data.

Example
<?php

require_once __DIR__ . '/../vendor/autoload.php';


$socket = new \HemiFrame\Lib\WebSocket\WebSocket("localhost", 8080);
$socket->setEnableLogging(true);

$client = $socket->connect();

$socket->on("receive", function (\HemiFrame\Lib\WebSocket\Client $client, $data) use ($socket) {
	var_dump($data);
});

$socket->loop();
Please check your logic. Usually, you should use PHP client to send data, not to receive.

**Comment by printpagestopdf** [comment]
Hi,
with your help I have got it running. But one more question, how to cancel the loop correctly? In my case it worked by calling stopServer (it worked although its a client). In my example below I am sending a string and closing after receiving a result. Is that correct?


$ret=false;
$socket = new \HemiFrame\Lib\WebSocket\WebSocket("localhost", $port);
$client = $socket->connect();
if($client)
{
	$socket->on("receive", function (\HemiFrame\Lib\WebSocket\Client $client, $data) use ($socket,&$ret) {
		$ret=$data;
		$socket->disconnectClient($client);
		$socket->stopServer();
	});
	$socket->sendData($client, $cmd);
	$socket->loop();				
}

**Comment by heminei** [comment]
Yes, it is correct. The method name, in this case, is not user friendly but works.

**Comment by printpagestopdf** [comment]
many thanks, works like a charm and doesn't make such annoying errors like the library I previously used.

Best Regards
 

    Am Dienstag, 5. Mai 2020, 19:32:53 MESZ hat Martin Bratvanov <notifications@github.com> Folgendes geschrieben:  
 
 


Yes, it is correct. The method name, in this case, is not user friendly but works.
