### ISSUE TITLE
Question : any documentation ?

### ISSUE THREAD

**Issue by mytsdrm** [heminei/php-websocket#3]
Hi, your code is awesome, will you provide some documentation ?

**Comment by heminei** [comment]
Hi, 
I have not more documentation. Write to me, what to document? Or if you want more examples? 
Thanks!

**Comment by mytsdrm** [comment]
thanks for your response, i need to understand how to use $socket->on("connect");
where i can send output to client when its connected.

**Comment by heminei** [comment]
You can send data with "sendData" method:

```php
<?php
require_once '../src/HemiFrame/Lib/WebSocket.php';
$socket = new \HemiFrame\Lib\WebSocket("localhost", 8080);
//Connect to web socket
$client = $socket->connect();
if ($client !== false) {
	$socket->sendData($client, "My data"); //Send your data
	$socket->disconnectClient($client); //Disconnect client
}
```

$socket->on("connect") is event. This event is triggered when a new client is connected. You can use it, in your PHP web socket server.

Please check the demo folder.

**Comment by mytsdrm** [comment]
thankyou, sorry for my late respond.. i'll inform you soon

**Comment by mytsdrm** [comment]
hi @heminei , here is mycode : 
I saved this as server.php

my scenario is : when client connected from browser, then this websocket send text "Hallooo" to browser. 

> server.php
require_once('lib/vendor/autoload.php');
use \HemiFrame\Lib\WebSocket\WebSocket;
$socket = new WebSocket("localhost", 8080);
$socket->setEnableLogging(true);
$socket->on("connect", function(\HemiFrame\Lib\WebSocket\Client $client) {
  $socket->sendData($client,"Hallooo");
});
$socket->startServer();

But, when i open localhost:8080 from browser, here is the error :
`PHP Notice:  Undefined variable: socket in /var/www/html/websocket/server.php on line 9
PHP Fatal error:  Uncaught Error: Call to a member function sendData() on null in /var/www/html/websocket/server.php:9
Stack trace:
#0 [internal function]: {closure}(Object(HemiFrame\Lib\WebSocket\Client))
#1 /var/www/html/websocket/lib/vendor/hemiframe/php-websocket/src/HemiFrame/Lib/WebSocket/WebSocket.php(556): call_user_func_array(Object(Closure), Array)
#2 /var/www/html/websocket/lib/vendor/hemiframe/php-websocket/src/HemiFrame/Lib/WebSocket/WebSocket.php(467): HemiFrame\Lib\WebSocket\WebSocket->trigger('connect', Array)
#3 /var/www/html/websocket/lib/vendor/hemiframe/php-websocket/src/HemiFrame/Lib/WebSocket/WebSocket.php(414): HemiFrame\Lib\WebSocket\WebSocket->loop()
#4 /var/www/html/websocket/server.php(11): HemiFrame\Lib\WebSocket\WebSocket->startServer()
#5 {main}
  thrown in /var/www/html/websocket/server.php on line 9
`

this error keep coming when i use $socket->on("connect")

please help to understand this .. thankyou

**Comment by amattu2** [comment]
In case you didn't solve it, you're missing the "use" statement in the connect function.

See Below:

>$socket->on("connect", function(\HemiFrame\Lib\WebSocket\Client $client) use($socket) {
>                $socket->sendData($client, "Hallooo");
> });
