### ISSUE TITLE
Undefined index 'type', handshake failure

### ISSUE THREAD

**Issue by amattu2** [heminei/php-websocket#5]
I occasionally get a PHP error "undefined index 'type' in Websocket.php:500", which results in a handshake failure. 

The error is for this line:
`
switch ($data['type']) {
`

The JavaScript error outputted is this:

> WebSocket connection to 'wss://my.xxxxxx.com/ws/' failed: A server must not mask any frames that it sends to the client.

It happens pretty consistently, but if I keep retrying the handshake, the client will connect.

**Comment by heminei** [comment]
Please, send me more details or an example. What is your PHP version?

**Comment by amattu2** [comment]
PHP Version:
> PHP 7.2.10-0

OS:
> Ubuntu 18.10

PHP Error:
> Undefined index: type in /var/[...]/WebSocket.php on line 500

The error is usually preceded (Before the error) by the following sequence:
> Handshake sent
> Connect
> disconnect: Code: 1002 => protocol error
> error: Resource temporarily unavailable
> disconnect: Code: 1003 => unknown data (opcode)

As I mentioned before, this doesn't happen every time. It's usually the first couple attempts, then it will connect. Let me know if I missed out anything. Line 500 in my code correlates to line 501 in the WebSocket.php source provided in the repo.

**Comment by amattu2** [comment]
Any ideas? I can't seem to find an order to this. Sometimes it will connect flawlessly on page load, sometimes it doesn't. 

I tried using a fallback for $data['type']:
`switch ($data['type'] ?: 'text') {`
But it didn't solve the handshake issue.

**Comment by heminei** [comment]
Please check with a new version: 1.6.1

**Comment by amattu2** [comment]
Still throws an undefined index error on line WebSocket.php:500. Seems more reliable, but the PHP error persists.

**Comment by heminei** [comment]
Please send sample code.

**Comment by amattu2** [comment]
> Please send sample code.

Of which files? WebSocket.php is identical to the on in the repo, as is Client.php.

**Comment by heminei** [comment]
Send me sample code when you use my library.

**Comment by amattu2** [comment]
Server.php
-- https://pastebin.com/fSKFyk3f

I attempted to use the built in code embed, but it ruined the markup.

**Comment by ASK-Lee** [comment]
> Server.php
> -- https://pastebin.com/fSKFyk3f
> 
> I attempted to use the built in code embed, but it ruined the markup.

I think you should use the sendData() function, and set the third parameter to false.

**Comment by heminei** [comment]
I can't find a problem in the sample. Can you send me a more detailed sample (server and client, cleared from not relevant code for this problem)?

**Comment by amattu2** [comment]
> I think you should use the sendData() function, and set the third parameter to false.

Partially fixed my issue. Now it's only happening 10-20% of the time, and it fixed the constant websocket closing issue (due to a masked frame). I no longer have the desire to even worry about it as my application has a very decent fallback solution. 

Closing this.
