### ISSUE TITLE
Does php client support add listen event?

### ISSUE THREAD

**Issue by ASK-Lee** [heminei/php-websocket#7]
Does the client support add listen event like javascript?
```
var wsUri = "ws://localhost:8080";
websocket = new WebSocket(wsUri);
websocket.onopen...
websocket.onmessage...
```
If support, then we can use php client as convenient as js websocket client.

**Comment by heminei** [comment]
Yes, the PHP client support events:

```
$socket->on("connect", function(\HemiFrame\Lib\WebSocket\Client $client) {
});

$socket->on("receive", function(\HemiFrame\Lib\WebSocket\Client $client, $data) {
});

$socket->on("send", function(\HemiFrame\Lib\WebSocket\Client $client, $data) {
});

$socket->on("ping", function(\HemiFrame\Lib\WebSocket\Client $client, $data) {
});

$socket->on("pong", function(\HemiFrame\Lib\WebSocket\Client $client, $data) {
});

$socket->on("disconnect", function(\HemiFrame\Lib\WebSocket\Client $client, $statusCode, $reason) {
});

$socket->on("error", function($socket, $client, $phpError, $errorMessage, $errorCode) {
});
```

**Comment by ASK-Lee** [comment]
I saw these code in demo client.php file and tried many times, it doesn't work. I didn't receive any message from server, but the brower client can receive the messages all the time, and I found the server indeed send messages to all clients, when I run the client.php, the server send two messages, one for the brower client, and one for the client.php script, but there is nothing output in the console. 
client.php
```
require_once './vendor/autoload.php';
set_time_limit(0);
$socket = new \HemiFrame\Lib\WebSocket\WebSocket('localhost', '7001');
$socket->on('receive', function (\HemiFrame\Lib\WebSocket\Client $client, $data) {
    echo $data."\n";
});
$client = $socket->connect();
$data = [
    'demo' => 'something'
];
//I don't know how to hold the script,so I use the loop + sleep statement
while (true) {
    $socket->sendData($client, json_encode($data));
    sleep(10);
}
```
![1](https://user-images.githubusercontent.com/9458169/49358554-117fef80-f70e-11e8-9594-7c653956bbe8.png)
![2](https://user-images.githubusercontent.com/9458169/49358569-1a70c100-f70e-11e8-8bc7-8f751c17ba19.png)
![3](https://user-images.githubusercontent.com/9458169/49358575-1e9cde80-f70e-11e8-99a4-c0fee67d35c9.png)

**Comment by ASK-Lee** [comment]
@heminei Can you help me check and test the problem above?
